name: support

services:
  app:
    container_name: app_support
    image: yqni13/support:v1.0.6 # keep version up-to-date
    build:
      context: .
      target: dev
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      # Refer to "localhost" outside of docker environment, otherwise docker volume is targeted.
      SECRET_DB_HOST: host.docker.internal
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
