name: support

services:
  app:
    image: yqni13/support:1.0
    build: .
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      SECRET_DB_LOCAL_HOST: host.docker.internal
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
