name: support

services:
  app:
    image: yqni13/support:v1.0.0 # keep version up-to-date
    build: .
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      # Refer to "localhost" outside of docker environment, otherwise docker volume is target.
      SECRET_DB_LOCAL_HOST: host.docker.internal
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
