export const Config: any = {
    ADMIN_API: process.env.SECRET_ADMIN_API || null,
    ENV_MODE: process.env.NODE_ENV || 'development',
    PORT: process.env.ENV_PORT || 3000,
    EMAIL_RECEIVER: process.env.SECRET_EMAIL_RECEIVER || null,
    EMAIL_SENDER: process.env.SECRET_EMAIL_SENDER || null,
    EMAIL_PASS: process.env.SECRET_EMAIL_PASS || null,
    PRIVATE_KEY_ARTDV: process.env.SECRET_PRIVATE_KEY_ARTDV || null,
    PRIVATE_KEY_TAVA: process.env.SECRET_PRIVATE_KEY_TAVA || null,
    BETTERSTACK_LOGGING_KEY: process.env.SECRET_BETTERSTACK_LOGGING_KEY || null,
    BETTERSTACK_HOST: process.env.SECRET_BETTERSTACK_HOST || null,
    DB_USER: process.env.SECRET_DB_USER || null,
    DB_PASS: process.env.SECRET_DB_PASS || null,
    DB_HOST: process.env.SECRET_DB_HOST || null,
    DB_PORT: process.env.SECRET_DB_PORT || null,
    DB_DATABASE: process.env.SECRET_DB_DATABASE || null,
    DB_TEST_USER: process.env.SECRET_DB_TEST_USER || null,
    DB_TEST_PASS: process.env.SECRET_DB_TEST_PASS || null,
    DB_TEST_HOST: process.env.SECRET_DB_TEST_HOST || null,
    DB_TEST_PORT: process.env.SECRET_DB_TEST_PORT || null,
    DB_TEST_DATABASE: process.env.SECRET_DB_TEST_DATABASE || null,
    TEST_APIKEY_RAW: process.env.SECRET_TEST_APIKEY_RAW || null,
    TEST_APIKEY_HASH: process.env.SECRET_TEST_APIKEY_HASH || null,
    RATELIMITS_CLIENTSBURSTLIMIT: process.env.SECRET_RATELIMITS_CLIENTSBURSTLIMIT || null,
    RATELIMITS_CLIENTSDAILYLIMIT: process.env.SECRET_RATELIMITS_CLIENTSDAILYLIMIT || null,
    RATELIMITS_USERSBURSTLIMIT: process.env.SECRET_RATELIMITS_USERSBURSTLIMIT || null,
    RATELIMITS_USERSDAILYLIMIT: process.env.SECRET_RATELIMITS_USERSDAILYLIMIT || null
};