export const ErrorCodes: any = {
    AuthSecretNotFoundException: 0,
    InvalidCredentialsException: 1,
    TokenMissingException: 2,
    JWTExpirationException: 3,
    AuthenticationStandardException: 4,
    AuthenticationEmailException: 5,
    InternalServerException: 6,
    RequestExceedMaxException: 7,
    UnexpectedException: 8,
    InvalidPropertiesException: 9,
    InvalidEndpointException: 10,
    UnimplementedException: 11,
    InvalidTokenException: 12,
    InvalidSourceException: 13,
    UnexpectedApiResponseException: 14,
    DBConnectionException: 15,
    DBEmptyException: 16,
    MaintenanceException: 17,
    MalformedApiKeyException: 18,
    ApiKeyMissingException: 19
};